# Optional: Add funding links for your open-source project
# Remove this file if you don't want funding buttons

# Example funding options:
# github: [yourusername]
# patreon: yourusername
# ko_fi: yourusername
# custom: ["https://yourwebsite.com/donate"]

